# Mandatory settings

name: Smart Women I Know
description: I've spent a career getting into people's heads, as a writer, a strategist, and a natural empathisizer to, well, basically everyone and everything. If I can say I've gained one thing it's that I've met a lot of really smart, clever, ingenious women who've accomplished a lot in their careers, but usually it's through a story that's even more interesting, inspiring and compelling.  These are the women I know you'll want to meet.  The women who, with humor, grace and a great deal of knowing see the world and work in the world creating profound change, big and small.  These are the women you wanna know. Really.  Just listen.
short_description: Smart women are succeeding wildly in business. But peel back the layers and they're so much more inspiring than a title tells you. Learn how.
author_name: Ellen Barnett
webmaster_email: email@example.com
paginate: 5
paginate_path: "/posts/page/:num/"
url: http://www.smartwomeniknow.com # add site url http://example.com/
blog_theme: light # Or use dark

itunes_catergory: Business
itunes_sub_catergory: Careers
itunes_tags: smart, women, i, know, business, female, leader,

# Optional settings

discus_identifier: # Add your Disqus identifier
ga_analytics: UA-67825496-9 # Add your GA Tracking Id
rss_enabled: true # Change to false if not
social:
  dribbble: # Add your Dribbble handle
  facebook: # Add your Facebook handle
  github: # Add your GitHub handle
  linkedin: # Add your LinkedIn handle
  twitter: # Add your Twitter handle
  email: # Add your Email address
  bitcoin: # Add your Bitcoin link or address

# Important settings (change at own risk)

assets:
  compress:
    css: true
    js: false
  features:
    automatic_img_size: false
  sources:
    - _assets/bower
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
collections:
  my_tags:
    output: true
    permalink: /tag/:slug/
defaults:
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: articles_by_tag
  -
    scope:
      type: posts
    values:
      layout: podcast
      description: ""
      podcast_url: ""
      podcast_listen_time: ""
      tags: []
exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
gems:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
permalink: posts/:slug
