---
name: Smart Women I Know
description: Description of the site for feed xml
short_description: Description that is shorter
author_name: Desired name here
webmaster_email: email@example.com
paginate: 3
paginate_path: "/posts/page/:num/"
url: 
blog_theme: light
itunes_catergory: Education
itunes_sub_catergory: Higher Education
itunes_tags: tag1, tag2, separate, by, commas,
discus_identifier: 
ga_analytics: 
rss_enabled: true
social:
  dribbble: 
  facebook: 
  github: 
  linkedin: 
  twitter: 
  email: 
  bitcoin: 
assets:
  compress:
    css: true
    js: true
  features:
    automatic_img_size: false
  sources:
  - _assets/bower
  - _assets/fonts
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets
  - _vendor/
collections:
  my_tags:
    output: true
    permalink: "/tag/:slug/"
defaults:
- scope:
    path: ''
    type: my_tags
  values:
    layout: articles_by_tag
- scope:
    type: posts
  values:
    layout: podcast
    description: ''
    podcast_url: ''
    podcast_listen_time: ''
    tags: []
exclude:
- ".bowerrc"
- ".travis.yml"
- bin/*
- bower.json
- circle.yml
- Gemfile
- Gemfile.lock
- README.md
- vendor/
gems:
- jekyll-assets
- jekyll-paginate
- jekyll-sitemap
permalink: posts/:slug
timezone: America/Los_Angeles
